@API_KEY = AIzaSyBgfAthbAtT0QR_9yz63J7NB-DDBu-pd4k
@ID_TASK = -MaKuyltfEsivhpSbLt9
@BASE_URL_AUTH = https://identitytoolkit.googleapis.com/v1

@USER_ID = oz9JLnXiWxcVELhKaqX6OBGuNeA3

@BASE_URL = https://auth-502e2-default-rtdb.firebaseio.com

@USER_TOKEN = eyJhbGciOiJSUzI1NiIsImtpZCI6IjNkOWNmYWE4OGVmMDViNDI0YmU2MjA1ZjQ2YjE4OGQ3MzI1N2JjNDIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aC01MDJlMiIsImF1ZCI6ImF1dGgtNTAyZTIiLCJhdXRoX3RpbWUiOjE2MjE4OTc2NzYsInVzZXJfaWQiOiJvejlKTG5YaVd4Y1ZFTGhLYXFYNk9CR3VOZUEzIiwic3ViIjoib3o5SkxuWGlXeGNWRUxoS2FxWDZPQkd1TmVBMyIsImlhdCI6MTYyMTg5ODQzNSwiZXhwIjoxNjIxOTAyMDM1LCJlbWFpbCI6InVzZXI1QHBlcnUucGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidXNlcjVAcGVydS5wZSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.DdkYmbyLwOP3n7XTPGi9sgowJWYGaOfvj5yOksOAApLuHfyPlebDuKjKRnlWvYDmEpa6T5YjknoPBrNdlQffmTJGPbydUyyvq-a8u5RWNFlR6fYwYToQFG5E3cnW5dWSJeka-JONrimH4uP0qBW30BcY1cSXXXuPTAevpW_0WwyWQzgvsCT1Npi04HD7Ng9mbjEFhBdxL4jxP37qciFv_cqnJVCCvjf8Lo9WGP1va3dV_2tyyhPsZ0gCRqu4ioEU1p0_HjLRdnruiQb0mT3w-GBOcqC18CDSqWJZgDDBOVcz3PxVtu8TCFjfq1X7x79XPIWlsdaYxUPDq_YcpXPuaw

@BASE_URL_REFRESH_TOKEN = https://securetoken.googleapis.com/v1


# {
#   "kind": "identitytoolkit#VerifyPasswordResponse",
#   "localId": "oz9JLnXiWxcVELhKaqX6OBGuNeA3",
#   "email": "user5@peru.pe",
#   "displayName": "",
#   "idToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjNkOWNmYWE4OGVmMDViNDI0YmU2MjA1ZjQ2YjE4OGQ3MzI1N2JjNDIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aC01MDJlMiIsImF1ZCI6ImF1dGgtNTAyZTIiLCJhdXRoX3RpbWUiOjE2MjE4OTc2NzYsInVzZXJfaWQiOiJvejlKTG5YaVd4Y1ZFTGhLYXFYNk9CR3VOZUEzIiwic3ViIjoib3o5SkxuWGlXeGNWRUxoS2FxWDZPQkd1TmVBMyIsImlhdCI6MTYyMTg5NzY3NiwiZXhwIjoxNjIxOTAxMjc2LCJlbWFpbCI6InVzZXI1QHBlcnUucGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidXNlcjVAcGVydS5wZSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.PJFk8q3EfSWW3NWeceoVoq1ghsPz2HCkYEbzX5m51jEdNKqZFRppO0lDZB3V2fe6LjQ2DDQ5wM4XWrFx4b7HFl3kwR30LAFkpoemW4gxanNFeYRv0DFiTp004XdlFoMTwGY4GkKwCmULNFd0IpCVEDNiKclnCAxeKzMaKusQqbHW-WGTdcERpMBU_BXQlkxXmSkosp1qH2Xth6aQHt-7K69J5L9GDHlx1UEQHRiwVkg8vECFjp0I1s0pcEogm5wup0xkwskHx3Cd4af6fmfgEnFVsja7tLkgR92ze0Qs-z63J2V4K3D5d3tNSL4vPN5fuJkAvnbpAfPLWNBERqgJbQ",
#   "registered": true,
#   "refreshToken": "AGEhc0B0SsXLPh-oMILe5EOIjdPWn_lKjTQJKNvt0t_DkywjU-XofPVtHALoxDvQGRt3sxqavJ0BA5G8i2qR4YiGtqz9Nl_-sUpn4uZcZLH1wHxpP2CrZSmWWzzzTHqSikfF_8cWUjWUbb7-t4DAgV1bTshLpUJaHJY_63m_Hl9EAY92aiQUhh6xkqQR4qtbatWU44HkJZpL",
#   "expiresIn": "3600"
# }
### Register user
POST {{BASE_URL_AUTH}}/accounts:signUp
?key=AIzaSyBgfAthbAtT0QR_9yz63J7NB-DDBu-pd4k
Content-Type: application/json

{
    "email": "user5@peru.pe",
    "password":"123456",
    "returnSecureToken":true
}

### Login User
POST {{BASE_URL_AUTH}}/accounts:signInWithPassword
?key=AIzaSyBgfAthbAtT0QR_9yz63J7NB-DDBu-pd4k
Content-Type: application/json

{
    "email": "user5@peru.pe",
    "password":"123456",
    "returnSecureToken":true
}



### Refresh token
POST {{BASE_URL_REFRESH_TOKEN}}/token
?key={{API_KEY}}
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token
&refresh_token=AGEhc0B0SsXLPh-oMILe5EOIjdPWn_lKjTQJKNvt0t_DkywjU-XofPVtHALoxDvQGRt3sxqavJ0BA5G8i2qR4YiGtqz9Nl_-sUpn4uZcZLH1wHxpP2CrZSmWWzzzTHqSikfF_8cWUjWUbb7-t4DAgV1bTshLpUJaHJY_63m_Hl9EAY92aiQUhh6xkqQR4qtbatWU44HkJZpL

### LIST TODO
GET {{BASE_URL}}/todo/{{USER_ID}}.json
?auth={{USER_TOKEN}}




### ADD TASK
POST {{BASE_URL}}/todo/{{USER_ID}}.json
?auth={{USER_TOKEN}}
Content-Type: application/json

{
    "description": "working?",
    "done":false
}

### EDIT TASK
PATCH  {{BASE_URL}}/todo/{{USER_ID}}/{{ID_TASK}}.json
?auth={{USER_TOKEN}}
Content-Type: application/json

{
    "description": "UPDATE",
    "done":false
}


### DELETE TASK
DELETE {{BASE_URL}}/todo/{{USER_ID}}/{{ID_TASK}}.json
?auth={{USER_TOKEN}}