@API_KEY = AIzaSyBgfAthbAtT0QR_9yz63J7NB-DDBu-pd4k
@ID_TASK = -MaKuyltfEsivhpSbLt9
@BASE_URL_AUTH = https://identitytoolkit.googleapis.com/v1

@USER_ID = oz9JLnXiWxcVELhKaqX6OBGuNeA3

@BASE_URL = https://auth-502e2-default-rtdb.firebaseio.com

@USER_TOKEN = eyJhbGciOiJSUzI1NiIsImtpZCI6IjNkOWNmYWE4OGVmMDViNDI0YmU2MjA1ZjQ2YjE4OGQ3MzI1N2JjNDIiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aC01MDJlMiIsImF1ZCI6ImF1dGgtNTAyZTIiLCJhdXRoX3RpbWUiOjE2MjE4MzYxNTcsInVzZXJfaWQiOiJvejlKTG5YaVd4Y1ZFTGhLYXFYNk9CR3VOZUEzIiwic3ViIjoib3o5SkxuWGlXeGNWRUxoS2FxWDZPQkd1TmVBMyIsImlhdCI6MTYyMTgzNjE1NywiZXhwIjoxNjIxODM5NzU3LCJlbWFpbCI6InVzZXI1QHBlcnUucGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidXNlcjVAcGVydS5wZSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.sgFyHiA3x6XWNEN407leR2BnWUVY70ji8wgB2Idn-g5wn8SelaJkJNN-QSPESOyzdVVC471jEOLcn2yuim32-abfK4XUK-28w2B1rjmVFEZXXDEZ72qEQ-5H5wy62OW9OKz9035qqqQRUN8SbHswGipxHnzx4JLf8TCLLV1MbstwD_RtZ6oM9AN8YWT661b2eO6NmEgB5ycK0dctQ4cE_GdFEgm39Y5NYuSrxODzCtPbYSeAu9OJRmA86znMNUhdGF_N1s89b2meEnTLR02tSmzwJFbXSbJ36dJLCgCweG7MDC8w0Q46fpsMBuhwoIJI695ksvyxgJaI-bSt5Fy4iA


### Register user
POST {{BASE_URL_AUTH}}/accounts:signUp
?key=AIzaSyBgfAthbAtT0QR_9yz63J7NB-DDBu-pd4k
Content-Type: application/json

{
    "email": "user5@peru.pe",
    "password":"123456",
    "returnSecureToken":true
}

### Login User
POST {{BASE_URL_AUTH}}/accounts:signInWithPassword
?key=AIzaSyBgfAthbAtT0QR_9yz63J7NB-DDBu-pd4k
Content-Type: application/json

{
    "email": "user5@peru.pe",
    "password":"123456",
    "returnSecureToken":true
}





### LIST TODO
GET {{BASE_URL}}/todo/{{USER_ID}}.json
?auth={{USER_TOKEN}}


### ADD TASK
POST {{BASE_URL}}/todo/{{USER_ID}}.json
?auth={{USER_TOKEN}}
Content-Type: application/json

{
    "description": "working?",
    "done":false
}

### EDIT TASK
PATCH  {{BASE_URL}}/todo/{{USER_ID}}/{{ID_TASK}}.json
?auth={{USER_TOKEN}}
Content-Type: application/json

{
    "description": "UPDATE",
    "done":false
}


### DELETE TASK
DELETE {{BASE_URL}}/todo/{{USER_ID}}/{{ID_TASK}}.json
?auth={{USER_TOKEN}}